! ESTE PROGRAMA CALCULARÁ EL HISTOGRAMA (DEGREE DISTRIBUTION) A PARTIR DEL ARCHIVO CON EL GRADO DE CADA NODO. ESTA CONSTRUIDO EN BASE A LA ESTRUCTURA QUE PRESENTAN LAS REDES CON LAS QUE TRABAJAREMOS. TAMBIÉN CALCULAMOS EL HISTOGRAMA LA DISTRIBUCION DE GRADO ACUMULADA
       PROGRAM HISTOGRAM
       IMPLICIT NONE
       REAL*8 EXPK,SUM2,SUM
       INTEGER*4 NDAT,BINS,K,I,J,N
       INTEGER*4, ALLOCATABLE :: DEGHIS(:), DEGREE(:)
       REAL*8, ALLOCATABLE :: PROB(:),CPROB(:),CCPROB(:)

!----------------------------LAYER 0---------------------------------
       NDAT = 1014
       BINS = 1014


       ALLOCATE(PROB(NDAT))
       ALLOCATE(DEGHIS(BINS))
       ALLOCATE(CPROB(NDAT))
       ALLOCATE(DEGREE(BINS))
       ALLOCATE(CCPROB(NDAT))

! INICIALIZAMOS LOS HISTOGRAMA
       PROB = 0.d0
       CPROB = 0.d0
       CCPROB = 0.d0
       SUM = 0.d0
       SUM2 = 0.d0

! LLAMAMOS EL VECTOR DE GRADOS
       OPEN(19, FILE = 'degrees0.txt')
       DO K = 1,NDAT
        READ(19,*) I,J
        DEGREE(K) = J
        SUM = SUM + DEGREE(K)
       ENDDO
       CLOSE(19)

! VALOR ESPERADO DE K
       EXPK = DBLE(SUM)/NDAT
       WRITE(*,*) 'layer 0'
       WRITE(*,*) '<k> = ', EXPK

!CALCULAMOS LAS PROBABILIDADES (FRECUENCIAS DEL HISTOGRAMA)
       DO I = 1, NDAT
        DO J = 1,NDAT
            IF (DEGREE(I).EQ.J) THEN
                PROB(J) = PROB(J)+1.d0!DEGREE DISTRIBUTION
            ENDIF
            IF (DEGREE(I).LE.J) THEN
                CPROB(J) = CPROB(J)+1.d0 !CUMULATIVE DEGREE DISTRIBUTION
            ENDIF
            IF (DEGREE(I).GT.J) THEN
                CCPROB(J) = CCPROB(J) +1.d0 ! COMPLEMENTARY CUMULATIVE DEGREE DISTRIBUTION
            ENDIF
        ENDDO
       ENDDO

! ELIMINAMOS VALORES DE LA CCDD SI SON IGUALES PARA QUE SEA MAS NITIDO EL GRAFICO
       DO I = 1,NDAT
        IF (CCPROB(I)==CCPROB(I+1))THEN
            CCPROB(I)=0.d0
        ENDIF
       ENDDO



! COORDENADAS ABCISAS Y NORMALIZAMOS HISTOGRAMA. ESCRIBIMOS LAS DOS VARIABLES EN UN ARCHIVO
       OPEN(25, FILE = 'degreedist0.txt')
       DO K = 1, NDAT
        DEGHIS(K) = K
        PROB(K) = PROB(K)/NDAT
        CPROB(K) = CPROB(K)/NDAT
        CCPROB(K) = CCPROB(K)/NDAT
        SUM2 = SUM2 + PROB(K)
        WRITE(25, *) DBLE(DEGHIS(K)/EXPK),PROB(K), CPROB(K), CCPROB(K)
       ENDDO
       CLOSE(25)
       WRITE(*,*) 'suma prob = ',SUM2
    

       ENDPROGRAM HISTOGRAM
